// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: cro_ids.sql

package db

import (
	"context"
)

const getCroidByCroid = `-- name: GetCroidByCroid :one
SELECT id, croid, cro_type, cro_value, system, created_at
FROM cro_ids
WHERE croid = ?
LIMIT 1
`

func (q *Queries) GetCroidByCroid(ctx context.Context, croid string) (CroID, error) {
	row := q.db.QueryRowContext(ctx, getCroidByCroid, croid)
	var i CroID
	err := row.Scan(
		&i.ID,
		&i.Croid,
		&i.CroType,
		&i.CroValue,
		&i.System,
		&i.CreatedAt,
	)
	return i, err
}

const getCroidByIdentity = `-- name: GetCroidByIdentity :one
SELECT id, croid, cro_type, cro_value, system, created_at
FROM cro_ids
WHERE cro_type = ? AND cro_value = ? AND system = ?
LIMIT 1
`

type GetCroidByIdentityParams struct {
	CroType  string
	CroValue string
	System   string
}

func (q *Queries) GetCroidByIdentity(ctx context.Context, arg GetCroidByIdentityParams) (CroID, error) {
	row := q.db.QueryRowContext(ctx, getCroidByIdentity, arg.CroType, arg.CroValue, arg.System)
	var i CroID
	err := row.Scan(
		&i.ID,
		&i.Croid,
		&i.CroType,
		&i.CroValue,
		&i.System,
		&i.CreatedAt,
	)
	return i, err
}

const insertCroid = `-- name: InsertCroid :exec
INSERT INTO cro_ids (croid, cro_type, cro_value, system, created_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertCroidParams struct {
	Croid     string
	CroType   string
	CroValue  string
	System    string
	CreatedAt string
}

func (q *Queries) InsertCroid(ctx context.Context, arg InsertCroidParams) error {
	_, err := q.db.ExecContext(ctx, insertCroid,
		arg.Croid,
		arg.CroType,
		arg.CroValue,
		arg.System,
		arg.CreatedAt,
	)
	return err
}
