// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

type CroID struct {
	ID        int64
	Croid     string
	CroType   string
	CroValue  string
	System    string
	CreatedAt string
}
