// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	GetCroidByCroid(ctx context.Context, croid string) (CroID, error)
	GetCroidByIdentity(ctx context.Context, arg GetCroidByIdentityParams) (CroID, error)
	InsertCroid(ctx context.Context, arg InsertCroidParams) error
}

var _ Querier = (*Queries)(nil)
