// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: items.sql

package db

import (
	"context"
)

const getItemByDOI = `-- name: GetItemByDOI :one
SELECT id, file, doi
FROM nauvis
WHERE doi = ?
LIMIT 1
`

func (q *Queries) GetItemByDOI(ctx context.Context, doi string) (Nauvis, error) {
	row := q.db.QueryRowContext(ctx, getItemByDOI, doi)
	var i Nauvis
	err := row.Scan(&i.ID, &i.File, &i.Doi)
	return i, err
}

const insertItem = `-- name: InsertItem :exec
INSERT INTO nauvis (file, doi)
VALUES (?, ?)
`

type InsertItemParams struct {
	File string
	Doi  string
}

func (q *Queries) InsertItem(ctx context.Context, arg InsertItemParams) error {
	_, err := q.db.ExecContext(ctx, insertItem, arg.File, arg.Doi)
	return err
}
