// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	GetItemByDOI(ctx context.Context, doi string) (Item, error)
	InsertItem(ctx context.Context, arg InsertItemParams) error
	WithTx(tx *sql.Tx) *Queries
}

var _ Querier = (*Queries)(nil)
