// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

type Dataset struct {
	ID           int64
	Source       string
	Version      string
	CollectedAt  string
	InitialInput string
	Output       string
}

type Latest struct {
	Source    string
	Version   string
	DatasetID int64
}
