// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	GetDataset(ctx context.Context, arg GetDatasetParams) (Dataset, error)
	GetLatest(ctx context.Context, source string) (GetLatestRow, error)
	InsertDataset(ctx context.Context, arg InsertDatasetParams) (sql.Result, error)
	ListDatasetsBySource(ctx context.Context, source string) ([]Dataset, error)
	ListLatest(ctx context.Context) ([]ListLatestRow, error)
	UpsertLatest(ctx context.Context, arg UpsertLatestParams) error
}

var _ Querier = (*Queries)(nil)
