site_name: systems/croid
theme:
  name: "material"
  palette:
    primary: black
  icon:
    logo: material/identifier
  favicon: images/xml.svg
nav:
  - CROID: "index.md"
plugins:
- mkdocstrings:
    default_handler: python
